from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from typing import Any, Protocol

from .data import DatasetPartition
from .services import LabService
from .store import iso_now
from .strategy import BacktestEngine, Strategy
from .simulator import VirtualBroker, OrderRequest, Side

logger = logging.getLogger(__name__)


class AIProvider(Protocol):
    def generate_strategy(self, context: dict[str, Any]) -> dict[str, Any]:
        ...

    def analyze_results(self, results: dict[str, Any]) -> str:
        ...


class MockAIProvider:
    """Simulates an LLM for Phase 6 unattended execution."""

    def __init__(self, model_id: str = "mock-llm-1.0"):
        self.model_id = model_id

    def generate_strategy(self, context: dict[str, Any]) -> dict[str, Any]:
        return {
            "hypothesis": "Simulated AI hypothesis: Buy first, hold, exit late.",
            "params": {"magic_number": 42},
            "entry_rule": "bar_idx == 0",
            "exit_rule": "bar_idx == len(bars) - 1"
        }

    def analyze_results(self, results: dict[str, Any]) -> str:
        return "Simulated AI Research Notes: The strategy showed deterministic outcomes."


class GeminiAIProvider:
    """Real LLM implementation using Google GenAI (Gemini)"""

    def __init__(self, api_key: str, model_id: str = "gemini-2.5-pro"):
        from google import genai
        self.client = genai.Client(api_key=api_key)
        self.model_id = model_id

    def generate_strategy(self, context: dict[str, Any]) -> dict[str, Any]:
        prompt = f"Given this trading lab context: {json.dumps(context, default=str)}, generate a simple test strategy spec as JSON."
        prompt += """
Return ONLY valid JSON in this format, without markdown blocks:
{
    "hypothesis": "String",
    "params": {"param_name": value},
    "entry_rule": "bar_idx == 0",
    "exit_rule": "bar_idx == len(bars) - 1"
}
"""
        try:
            response = self.client.models.generate_content(
                model=self.model_id,
                contents=prompt
            )
            text = response.text.strip()
            if text.startswith("```json"): text = text[7:]
            if text.startswith("```"): text = text[3:]
            if text.endswith("```"): text = text[:-3]
            
            return json.loads(text.strip())
        except Exception as e:
            logger.error(f"Failed to generate strategy with Gemini: {e}")
            return MockAIProvider().generate_strategy(context)

    def analyze_results(self, results: dict[str, Any]) -> str:
        prompt = f"Analyze these backtest results and provide brief research notes: {json.dumps(results)}"
        try:
            response = self.client.models.generate_content(
                model=self.model_id,
                contents=prompt
            )
            return response.text.strip()
        except Exception as e:
            logger.error(f"Failed to analyze results with Gemini: {e}")
            return f"Failed to generate notes: {e}"


class AIStrategy(Strategy):
    """An executable strategy generated by the AI."""

    def __init__(self, id: str, version: int, spec: dict[str, Any]):
        super().__init__(id, version, spec.get("params", {}))
        self.spec = spec
        self._hypothesis = spec.get("hypothesis", "No hypothesis")

    @property
    def hypothesis(self) -> str:
        return self._hypothesis

    def on_bar(self, broker: VirtualBroker, bar_idx: int, partition: DatasetPartition) -> None:
        bar = partition.bars[bar_idx]
        
        # Simulated parsing of simple rules
        if bar_idx == 0:
            req = OrderRequest(
                symbol=bar.symbol,
                side=Side.BUY,
                quantity=1,
                requested_price=bar.close,
                strategy_id=self.id,
                strategy_version=self.version,
                reason="ai_entry"
            )
            broker.submit_market_order(req)
        elif bar_idx == len(partition.bars) - 1:
            req = OrderRequest(
                symbol=bar.symbol,
                side=Side.SELL,
                quantity=1,
                requested_price=bar.close,
                strategy_id=self.id,
                strategy_version=self.version,
                reason="ai_exit"
            )
            broker.submit_market_order(req)


@dataclass
class ResearchLoop:
    lab: LabService
    engine: BacktestEngine
    ai: AIProvider

    def run_experiment(self, experiment_id: str, partition: DatasetPartition) -> None:
        # 1. Read context
        context = {"state": self.lab.state()}
        
        # 2. Generate
        spec = self.ai.generate_strategy(context)
        
        # 3. Create versioned candidate (Immutable)
        strategy_id = f"ai_strat_{experiment_id}"
        version = 1
        
        # Persist strategy spec
        self.lab.store.create_immutable_strategy_version(strategy_id, version, spec)
        
        # 4. Run deterministic experiment
        strat = AIStrategy(strategy_id, version, spec)
        results = self.engine.run(strat, partition)
        
        result_dict = {
            "net_pnl": str(results.net_pnl),
            "win_rate": results.win_rate,
            "total_trades": results.total_trades
        }
        
        # 5. Validate & 6. Store
        self.lab.store.create_immutable_experiment(experiment_id, {
            "strategy_id": strategy_id,
            "version": version,
            "results": result_dict
        })
        
        # 9. Generate notes
        notes = self.ai.analyze_results(result_dict)
        self.lab.store.append_event("AI_RESEARCH_NOTE", {"experiment_id": experiment_id, "notes": notes})
